from fpdf import FPDF
import io
import datetime

class PDFReport(FPDF):
    def header(self):
        # Header banner
        self.set_fill_color(18, 24, 38) # Dark blue / dark gray
        self.rect(0, 0, 210, 40, 'F')
        
        # Logo text
        self.set_text_color(255, 255, 255)
        self.set_font('Helvetica', 'B', 20)
        self.cell(0, 5, 'PHISHGUARD AI', ln=True)
        self.set_font('Helvetica', '', 10)
        self.cell(0, 8, 'Threat Intelligence & Website Analysis Report', ln=True)
        
        # Line break
        self.ln(12)
        
    def footer(self):
        # Position at 1.5 cm from bottom
        self.set_y(-15)
        self.set_font('Helvetica', 'I', 8)
        self.set_text_color(128, 128, 128)
        self.cell(0, 10, f'Page {self.page_no()} | Generated by PhishGuard AI on {datetime.date.today().strftime("%Y-%m-%d")}', align='C')

def generate_pdf_report(scan_data: dict) -> bytes:
    pdf = PDFReport()
    pdf.add_page()
    pdf.set_auto_page_break(auto=True, margin=15)
    
    # 1. Summary Section
    pdf.set_font('Helvetica', 'B', 14)
    pdf.set_text_color(18, 24, 38)
    pdf.cell(0, 10, 'Scan Summary', ln=True)
    pdf.set_draw_color(18, 24, 38)
    pdf.line(10, pdf.get_y(), 200, pdf.get_y())
    pdf.ln(4)
    
    # URL and Timestamp
    pdf.set_font('Helvetica', '', 10)
    pdf.set_text_color(50, 50, 50)
    pdf.cell(40, 6, 'Target URL:', 0)
    pdf.set_font('Helvetica', 'B', 10)
    pdf.cell(0, 6, scan_data["url"], 1, ln=True)
    pdf.set_font('Helvetica', '', 10)
    pdf.cell(40, 6, 'Analysis Domain:', 0)
    pdf.cell(0, 6, scan_data["domain"], 0, ln=True)
    pdf.cell(40, 6, 'Time of Scan:', 0)
    pdf.cell(0, 6, datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S UTC"), 0, ln=True)
    pdf.ln(4)
    
    # Risk Badge
    score = scan_data["risk_score"]
    pred = scan_data["prediction"]
    
    if pred == "Safe":
        bg_color = (46, 204, 113) # Green
        text_color = (255, 255, 255)
    elif pred == "Suspicious":
        bg_color = (241, 196, 15) # Yellow
        text_color = (0, 0, 0)
    else:
        bg_color = (231, 76, 60) # Red
        text_color = (255, 255, 255)
        
    pdf.set_fill_color(*bg_color)
    pdf.set_text_color(*text_color)
    pdf.set_font('Helvetica', 'B', 12)
    pdf.cell(190, 10, f"CLASSIFICATION: {pred.upper()} | RISK SCORE: {score}/100", 0, 1, 'C', True)
    pdf.ln(6)
    
    # 2. XAI / Threat Factors
    pdf.set_font('Helvetica', 'B', 12)
    pdf.set_text_color(18, 24, 38)
    pdf.cell(0, 8, 'Threat Factors & Explainable AI Insights', ln=True)
    pdf.set_draw_color(18, 24, 38)
    pdf.line(10, pdf.get_y(), 200, pdf.get_y())
    pdf.ln(3)
    
    pdf.set_font('Helvetica', '', 10)
    pdf.set_text_color(50, 50, 50)
    if scan_data.get("reasons"):
        for reason in scan_data["reasons"]:
            pdf.multi_cell(0, 6, f"- {reason}", new_x="LMARGIN", new_y="NEXT")
    else:
        pdf.cell(0, 6, 'No significant threat factors found. The URL appears clean.', ln=True)
    pdf.ln(6)
    
    # 3. Technical Breakdown (WHOIS & SSL)
    pdf.set_font('Helvetica', 'B', 12)
    pdf.set_text_color(18, 24, 38)
    pdf.cell(0, 8, 'Technical Intelligence', ln=True)
    pdf.line(10, pdf.get_y(), 200, pdf.get_y())
    pdf.ln(3)
    
    # WHOIS
    whois_data = scan_data.get("whois_info", {})
    pdf.set_font('Helvetica', 'B', 10)
    pdf.cell(0, 6, 'WHOIS Registration:', ln=True)
    pdf.set_font('Helvetica', '', 10)
    pdf.cell(50, 6, f" Registrar: {whois_data.get('registrar', 'Unknown')}", 0)
    pdf.cell(50, 6, f" Country: {whois_data.get('country', 'Unknown')}", ln=True)
    pdf.cell(50, 6, f" Creation Date: {whois_data.get('creation_date', 'Unknown')[:10]}", 0)
    pdf.cell(50, 6, f" Domain Age: {whois_data.get('domain_age_days', 'Unknown')} days", ln=True)
    pdf.ln(3)
    
    # SSL
    ssl_data = scan_data.get("ssl_info", {})
    pdf.set_font('Helvetica', 'B', 10)
    pdf.cell(0, 6, 'SSL/TLS Certificate:', ln=True)
    pdf.set_font('Helvetica', '', 10)
    status_ssl = "Valid" if ssl_data.get("valid") else "Invalid/None"
    pdf.cell(50, 6, f" Certificate Status: {status_ssl}", 0)
    pdf.cell(100, 6, f" Issuer: {ssl_data.get('issuer', 'None')}", ln=True)
    pdf.cell(50, 6, f" Expiration Date: {ssl_data.get('expiration_date', 'None')[:10]}", ln=True)
    pdf.ln(3)
    
    # DNS
    dns_data = scan_data.get("dns_info", {})
    pdf.set_font('Helvetica', 'B', 10)
    pdf.cell(0, 6, 'DNS Resolution:', ln=True)
    pdf.set_font('Helvetica', '', 10)
    resolved_ips = ", ".join(dns_data.get("ips", [])) if dns_data.get("ips") else "None"
    pdf.cell(0, 6, f" Resolved IP Address(es): {resolved_ips}", ln=True)
    pdf.cell(0, 6, f" Hosting Provider: {dns_data.get('hosting_provider', 'Unknown')}", ln=True)
    pdf.ln(6)
    
    # Disclaimer
    pdf.set_font('Helvetica', 'I', 8)
    pdf.set_text_color(150, 150, 150)
    pdf.multi_cell(190, 4, "Disclaimer: This threat report is generated automatically by PhishGuard AI using machine learning models and heuristics. While we strive for absolute accuracy, threat indicators may evolve, and users should exercise caution when visiting flagged resources.")
    
    # Output to bytes
    pdf_bytes = pdf.output()
    if isinstance(pdf_bytes, str):
        # In some versions of fpdf2 it returns a string, convert to bytes
        return pdf_bytes.encode('latin1')
    return pdf_bytes
